# Python 3.8.0

FROM python:3

# author of file
LABEL maintainer="Zhiyuan (Andrew) Wang <wangzyzju@gmail.com>"

# Packages that we need
WORKDIR /usr/src/app
COPY requirements.txt ./
COPY requirements ./requirements

# instruction to be run during image build
RUN pip install -r requirements.txt

# Copy all the files from current source directory(from your system) to
# Docker container in /usr/src/app directory
COPY db/config.ini .
COPY funwithflags/. ./funwithflags
COPY main.py .

# Setup port
ENV PORT=8080

# Command to startup the container
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8080", "main"]
